### ISSUE TITLE
Final Capstone - Setup Kanban Board

### ISSUE THREAD

**Issue by BahirHakimy** [BahirHakimy/rent-a-car#12]
- We are two members in this project
- @Dadadon
-  @BahirHakimy 
- Here is the link to [Kanban Board](https://github.com/users/BahirHakimy/projects/4)
- And here is the initial screenshot

![Screenshot 2023-07-20 213435](https://github.com/BahirHakimy/rent-a-car/assets/73453971/c8fc0490-fd21-40b2-afa6-9b7dda3d135d)

**Comment by Meltrust** [comment]
Hi @BahirHakimy ,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, fair pointings, and have been assigned ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
